### ISSUE TITLE
Annoying clicks in abcjs playback

### ISSUE THREAD

**Issue by SteveALee** [music-practice-tools/music-practice-tools#1]
Play any of the [tune scores](https://musicpracticetools.net/tunes/brown-eyed-girl/) and clicks are heard at the ends of notes.

**Comment by SteveALee** [comment]
Notes for @paulrosen

abcjs version v5.11.0

See developer notes in [Readme](https://github.com/music-practice-tools/music-practice-tools/blob/master/README.md). 

The source code is for abcjs is split between [server-side](https://github.com/music-practice-tools/music-practice-tools/blob/master/src/_11ty/add-shortcodes.js#L118-L144) and [client-side](https://github.com/music-practice-tools/music-practice-tools/blob/master/src/js/client.js#L237-L380). 

You can always hack on the built site files in `_site`

**Comment by paulrosen** [comment]
I updated the abcjs version to v6.0.0-beta.12 and the clicking went away.

I haven't used eleventy before so I'm not sure how you would do this, but since you are in the node ecosystem why don't you just include `"abcjs": "6.0.0-beta.12"` in your package.json file? Then upgrades would be easier.

I didn't see how to include it on the client side though - I guess it must have to get included with the other `require` statements and passed to the client.

**Comment by SteveALee** [comment]
11ty just builds a static site to `_site`

The client side is completely free of node ecosystem :) For now at least, I use good old global scripts I think one of the packages I used requires that and when I tried node it get it soon got messy. Same with using client side ES6 modules. Plus I wanted to avoid the entire bundling blah blah shebang for now. Snowpack looks fun for dev but bundles for release.

I also usually manually update my package dependencies as I got so messed by people not adhering to semver. I just remove the "^" from the versions and use a VS Code plugin to check version when I fee like it. 

So I'll grab that beta and update the [main HTML template](https://github.com/music-practice-tools/music-practice-tools/blob/master/src/_layouts/base.html.njk#L14) to use it. Is it nice and stable now? 

Thanks for the support.

PS I noticed lots more js files in the release zip but could find no explanation - are they at all interesting or just for various uses cases?

**Comment by SteveALee** [comment]
It's using a different voice - sounds like piano and much louder. That would explain the lack of clicks I guess

I've published a version of the main template that includes both version with one commentd out. Find it in `\music-practice-tools\src\_layouts\base.html.njk` and the JS goes in `music-practice-tools\src\js\3rdparty`

Thanks

**Comment by SteveALee** [comment]
See also https://github.com/paulrosen/abcjs/issues/453

**Comment by SteveALee** [comment]
I added a `Show ABC Source` check boxes to the Tunes pages in case it helps

**Comment by SteveALee** [comment]
PS I settign the voice with `[I: MIDI=program 33]`

**Comment by paulrosen** [comment]
I don't know if it matters, but the `K:` line should be the last header line. Sometimes commands act differently in the header and body. And `%%MIDI program 33` is the format that is usually used for a header line. The `I:` commands are for inline.

But in any case, try different numbers for the program and see if the sound changes for each number. That will tell whether the command has any effect.

Also in the ABC world the instruments are zero-based so you probably meant program 32 which is acoustic bass. But FWIW, it sounded like a bass to me. I don't know if there is something else different about our systems.

**Comment by SteveALee** [comment]
Well when I only change the script the sound changes.

Do you support %%midi? I didnt spot it in the source. Someone pointed me to I on one of you issues.

The trouble is that without any clear demarcation between header and body that I could be in either. As it worked I assumed was treated as inline, just at the start of the body.

I actually tried 32 and 33 and keep changing my mind :)

I'll explore more tomorrow. Thanks again.

**Comment by SteveALee** [comment]
so I changed the header as you suggested - 

```
X: 1
M: 4/4
Q: 1/4=85
L: 1/8
C: D'Angelo
T: Lady
R: Neo Soul
%%MIDI program 33
K: Eb clef=bass transpose=-12
```

So yes changing the MIDI program works, but I still get a difference voice when I switch to 6.0.0 Beta 12. The paino likeness is most noticable toward top of the bass clef. I used the abcjs file in the release zip..

**Comment by SteveALee** [comment]
Ahah! the new script is switching the sound font back to Fluid. I'll explore how I'm setting the soundfont.

**Comment by SteveALee** [comment]
So the code sets the soundfont in the call [`CreateSynth`](https://github.com/music-practice-tools/music-practice-tools/blob/25efa6afdc6b072782628997567a41d630c227d3/src/js/client.js#L395-L408), not [`loadTune`](https://github.com/music-practice-tools/music-practice-tools/blob/25efa6afdc6b072782628997567a41d630c227d3/src/js/client.js#L320-L336). That works for both clicking on a note before playing and playing. 

`soundFontUrl:
            'https://paulrosen.github.io/midi-js-soundfonts/MusyngKite/'`

I just tried setting the soundfont in both calls but it still loads Fluid not Musyng

So did the API change - or perhaps a soundfont bug got introduced?

**Comment by SteveALee** [comment]
So the API changed with the soundfont now being in a [new sub options object](https://github.com/paulrosen/abcjs/blob/v6.0.0-beta.12/src/synth/create-synth.js#L54-L55) :)

Is working perfectly now with NO CLICKS!!! \0/ Seems louder too.

Thanks
